export const GET_CAREGIVERS = 'GET_CAREGIVERS'
export const GET_CAREGIVERS_REQUEST = 'GET_CAREGIVERS_REQUEST'
export const GET_CAREGIVERS_SUCCESS = 'GET_CAREGIVERS_SUCCESS'
export const GET_CAREGIVERS_FAILURE = 'GET_CAREGIVERS_FAILURE'

export const DELETE_CAREGIVER = 'DELETE_CAREGIVER'
export const DELETE_CAREGIVER_REQUEST = 'DELETE_CAREGIVER_REQUEST'
export const DELETE_CAREGIVER_SUCCESS = 'DELETE_CAREGIVER_SUCCESS'
export const DELETE_CAREGIVER_FAILURE = 'DELETE_CAREGIVER_FAILURE'

export const SAVE_CAREGIVER = 'SAVE_CAREGIVER'
export const SAVE_CAREGIVER_REQUEST = 'SAVE_CAREGIVER_REQUEST'
export const SAVE_CAREGIVER_SUCCESS = 'SAVE_CAREGIVER_SUCCESS'
export const SAVE_CAREGIVER_FAILURE = 'SAVE_CAREGIVER_FAILURE'

export const UPDATE_CAREGIVER = 'UPDATE_CAREGIVER'
export const UPDATE_CAREGIVER_REQUEST = 'UPDATE_CAREGIVER_REQUEST'
export const UPDATE_CAREGIVER_SUCCESS = 'UPDATE_CAREGIVER_SUCCESS'
export const UPDATE_CAREGIVER_FAILURE = 'UPDATE_CAREGIVER_FAILURE'