export const VERIFY_USER = 'VERIFY_USER'
export const VERIFY_USER_REQUEST = 'VERIFY_USER_REQUEST'
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS'
export const VERIFY_USER_FAILURE = 'VERIFY_USER_FAILURE'
