export const SAVE_MEDICATION = 'SAVE_MEDICATION'
export const SAVE_MEDICATION_REQUEST = 'SAVE_MEDICATION_REQUEST'
export const SAVE_MEDICATION_SUCCESS = 'SAVE_MEDICATION_SUCCESS'
export const SAVE_MEDICATION_FAILURE = 'SAVE_MEDICATION_FAILURE'

export const UPDATE_MEDICATION = 'UPDATE_MEDICATION'
export const UPDATE_MEDICATION_REQUEST = 'UPDATE_MEDICATION_REQUEST'
export const UPDATE_MEDICATION_SUCCESS = 'UPDATE_MEDICATION_SUCCESS'
export const UPDATE_MEDICATION_FAILURE = 'UPDATE_MEDICATION_FAILURE'

export const DELETE_MEDICATION = 'DELETE_MEDICATION'
export const DELETE_MEDICATION_REQUEST = 'DELETE_MEDICATION_REQUEST'
export const DELETE_MEDICATION_SUCCESS = 'DELETE_MEDICATION_SUCCESS'
export const DELETE_MEDICATION_FAILURE = 'DELETE_MEDICATION_FAILURE'