export const GET_MED_LIST_W_SIDE_EFFECTS = 'GET_MED_LIST_W_SIDE_EFFECTS'
export const GET_MED_LIST_W_SIDE_EFFECTS_REQUEST = 'GET_MED_LIST_W_SIDE_EFFECTS_REQUEST'
export const GET_MED_LIST_W_SIDE_EFFECTS_SUCCESS = 'GET_MED_LIST_W_SIDE_EFFECTS_SUCCESS'
export const GET_MED_LIST_W_SIDE_EFFECTS_FAILURE = 'GET_MED_LIST_W_SIDE_EFFECTS_FAILURE'

export const GET_MEDICINE_LIST = 'GET_MEDICINE_LIST'
export const GET_MEDICINE_LIST_REQUEST = 'GET_MEDICINE_LIST_REQUEST'
export const GET_MEDICINE_LIST_SUCCESS = 'GET_MEDICINE_LIST_SUCCESS'
export const GET_MEDICINE_LIST_FAILURE = 'GET_MEDICINE_LIST_FAILURE'

export const CREATE_MED_LIST = 'CREATE_MED_LIST'
export const CREATE_MED_LIST_REQUEST = 'CREATE_MED_LIST_REQUEST'
export const CREATE_MED_LIST_SUCCESS = 'CREATE_MED_LIST_SUCCESS'
export const CREATE_MED_LIST_FAILURE = 'CREATE_MED_LIST_FAILURE'

export const ADD_MEDICINE_TO_MED_LIST = 'ADD_MEDICINE_TO_MED_LIST'
export const ADD_MEDICINE_TO_MED_LIST_REQUEST = 'ADD_MEDICINE_TO_MED_LIST_REQUEST'
export const ADD_MEDICINE_TO_MED_LIST_SUCCESS = 'ADD_MEDICINE_TO_MED_LIST_SUCCESS'
export const ADD_MEDICINE_TO_MED_LIST_FAILURE = 'ADD_MEDICINE_TO_MED_LIST_FAILURE'