export const GET_MED_PLANS = 'GET_MED_PLANS'
export const GET_MED_PLANS_REQUEST = 'GET_MED_PLANS_REQUEST'
export const GET_MED_PLANS_SUCCESS = 'GET_MED_PLANS_SUCCESS'
export const GET_MED_PLANS_FAILURE = 'GET_MED_PLANS_FAILURE'

export const CREATE_MED_PLAN = 'CREATE_MED_PLAN'
export const CREATE_MED_PLAN_REQUEST = 'CREATE_MED_PLAN_REQUEST'
export const CREATE_MED_PLAN_SUCCESS = 'CREATE_MED_PLAN_SUCCESS'
export const CREATE_MED_PLAN_FAILURE = 'CREATE_MED_PLAN_FAILURE'