export const SAVE_PATIENT = 'SAVE_PATIENT'
export const SAVE_PATIENT_REQUEST = 'SAVE_PATIENT_REQUEST'
export const SAVE_PATIENT_SUCCESS = 'SAVE_PATIENT_SUCCESS'
export const SAVE_PATIENT_FAILURE = 'SAVE_PATIENT_FAILURE'

export const DELETE_PATIENT = 'DELETE_PATIENT'
export const DELETE_PATIENT_REQUEST = 'DELETE_PATIENT_REQUEST'
export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS'
export const DELETE_PATIENT_FAILURE = 'DELETE_PATIENT_FAILURE'

export const UPDATE_PATIENT = 'UPDATE_PATIENT'
export const UPDATE_PATIENT_REQUEST = 'UPDATE_PATIENT_REQUEST'
export const UPDATE_PATIENT_SUCCESS = 'UPDATE_PATIENT_SUCCESS'
export const UPDATE_PATIENT_FAILURE = 'UPDATE_PATIENT_FAILURE'

export const ASSIGN_CAREGIVER = 'ASSIGN_CAREGIVER'
export const ASSIGN_CAREGIVER_REQUEST = 'ASSIGN_CAREGIVER_REQUEST'
export const ASSIGN_CAREGIVER_SUCCESS = 'ASSIGN_CAREGIVER_SUCCESS'
export const ASSIGN_CAREGIVER_FAILURE = 'ASSIGN_CAREGIVER_FAILURE'