export const GET_PATIENTS_OF_DOCTOR = 'GET_PATIENTS_OF_DOCTOR'
export const GET_PATIENTS_OF_DOCTOR_REQUEST = 'GET_PATIENTS_OF_DOCTOR_REQUEST'
export const GET_PATIENTS_OF_DOCTOR_SUCCESS = 'GET_PATIENTS_OF_DOCTOR_SUCCESS'
export const GET_PATIENTS_OF_DOCTOR_FAILURE = 'GET_PATIENTS_OF_DOCTOR_FAILURE'
