export const SAVE_SIDE_EFFECT = 'SAVE_SIDE_EFFECT'
export const SAVE_SIDE_EFFECT_REQUEST = 'SAVE_SIDE_EFFECT_REQUEST'
export const SAVE_SIDE_EFFECT_SUCCESS = 'SAVE_SIDE_EFFECT_SUCCESS'
export const SAVE_SIDE_EFFECT_FAILURE = 'SAVE_SIDE_EFFECT_FAILURE'

export const SAVE_SIDE_EFFECTS_LIST = 'SAVE_SIDE_EFFECTS_LIST'
export const SAVE_SIDE_EFFECTS_LIST_REQUEST = 'SAVE_SIDE_EFFECTS_LIST_REQUEST'
export const SAVE_SIDE_EFFECTS_LIST_SUCCESS = 'SAVE_SIDE_EFFECTS_LIST_SUCCESS'
export const SAVE_SIDE_EFFECTS_LIST_FAILURE = 'SAVE_SIDE_EFFECTS_LIST_FAILURE'

export const GET_SIDE_EFFECTS_LIST = 'GET_SIDE_EFFECTS_LIST'
export const GET_SIDE_EFFECTS_LIST_REQUEST = 'GET_SIDE_EFFECTS_LIST_REQUEST'
export const GET_SIDE_EFFECTS_LIST_SUCCESS = 'GET_SIDE_EFFECTS_LIST_SUCCESS'
export const GET_SIDE_EFFECTS_LIST_FAILURE = 'GET_SIDE_EFFECTS_LIST_FAILURE'

export const GET_SIDE_EFFECTS_OF_MEDICINE = 'GET_SIDE_EFFECTS_OF_MEDICINE'
export const GET_SIDE_EFFECTS_OF_MEDICINE_REQUEST = 'GET_SIDE_EFFECTS_OF_MEDICINE_REQUEST'
export const GET_SIDE_EFFECTS_OF_MEDICINE_SUCCESS = 'GET_SIDE_EFFECTS_OF_MEDICINE_SUCCESS'
export const GET_SIDE_EFFECTS_OF_MEDICINE_FAILURE = 'GET_SIDE_EFFECTS_OF_MEDICINE_FAILURE'